apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: motion-detection
  name: motion-detection
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: motion-detection
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: motion-detection
    spec:
      hostNetwork: true
      nodeSelector:
        type: led
      containers:
      - name: motion-detection
        image: 192.168.43.145:5000/motion-detection:v1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["python3","-u", "/motion-detection/detec_fram.py"]
        volumeMounts:
          - name: video-data
            mountPath: /dev/video0
      restartPolicy: Always
      volumes:
        - name: video-data
          hostPath:
            path: /dev/video0
status: {}