apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-led-light-mapper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-led-light-mapper
  template:
    metadata:
      labels:
        app: face-led-light-mapper
    spec:
      nodeSelector:
        type: led
      hostNetwork: true
      containers:
      - name: face-led-light-mapper-container
        image: 192.168.43.145:5000/face-led-light-mapper:v1.2
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /opt/kubeedge/
        - name: gpiomem
          mountPath: /dev/gpiomem
        - name: mem
          mountPath: /dev/mem
      volumes:
      - name: gpiomem
        hostPath:
          path: /dev/gpiomem
      - name: mem
        hostPath:
          path: /dev/mem
      - name: config-volume
        configMap:
          name: device-profile-config-pi-led
      restartPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: led-light
  namespace: default
rules:
- apiGroups: ["devices.kubeedge.io"]
  resources: ["devices"]
  verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: led-light-rbac
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: led-light
  apiGroup: rbac.authorization.k8s.io
